name: Docker-Build-Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      # source https://github.com/docker/build-push-action
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ../../Dockerfile
          push: false

      # - name: Set up Docker
      #   uses: docker/setup-docker@v2
      #   with:
      #     dockerfile: ../../Dockerfile

      # - name: Build Docker Image
      #   run: docker build -t testrepo:latest .
