name: Bazel Build and Run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Cache Bazelisk-Download
        uses: actions/cache@v2
        env:
          cache-name: bazel-cache
        with:
          path: ~/.cache/bazelisk
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-development

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Project
        run: |
          bazel build //app //graph

      - name: Run tests
        run: |
          bazel test //graph/...
