name: Bazel Build and Run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Bazel
        uses: abhinavsingh/setup-bazel@v3

      - name: Use Bazel (non-Windows)
        run: bazel -h

      - name: Build Project
        run: |
          bazel build //app //graph
      
      - name: Run App
        run: |
          bazel run //app
