name: Bazel Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Bazel
        run: |
          # Install Bazel (if not already installed)
          sudo apt-get update
          sudo apt-get install bazel

      - name: Build Project
        run: |
          bazel build //app
