name: Bazel Tests

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Bazel
        uses: abhinavsingh/setup-bazel@v3

      - name: Use Bazel (non-Windows)
        run: bazel -h

      - name: Build and Test
        run: |
          # Build and test your Bazel targets
          bazel test //graph/...
